### ISSUE TITLE
Add Garden and Plant schemas to Mongoose for initial setup

### ISSUE THREAD

**Issue by kanhegaonkarsaurabh** [kanhegaonkarsaurabh/growio-api#2]
* [] Add Garden and Plant schemas
* [] create the id's and create empty objects in the db

**Comment by kanhegaonkarsaurabh** [comment]
1. Create a feature branch: gp-schemas
2. Inside the models/ 

* create two files called garden.js and plant.js
* Use user.js as a reference to create a Mongoose schema for the above two. 
* import these in models/index.js so that they can be used later.

**Comment by yashgarde** [comment]
Created plant and garden mongoose schemas according to current database schema and imported the models into the models/index.js for later use.

**Comment by yashgarde** [comment]
Fixed: gp-schemas branched from auth. Now branched from master.
Added: new abstracted schema for plants in user specific gardens. Only imported by Garden schema and not entire database for now.

**Comment by kanhegaonkarsaurabh** [comment]
Merged
